blogs/urls.py
from django.urls import path
from .views import BlogTemplateView, BlogDetailView, create_post_comment

app_name = 'blogs'

urlpatterns = [
    path('', BlogTemplateView.as_view(), name='list'),
    path('detail/<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('post/<int:pk>/comment', create_post_comment, name='post_comment' )
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/urls.py
from django.urls import path
from .views import ContactTemplateView, CreateContactView

app_name = 'contacts'

urlpatterns = [
    path('', ContactTemplateView.as_view(), name='page'),
    path('create_contanct/', CreateContactView.as_view(), name='create_contanct')
]

pages/urls.py
from django.urls import path
from .views import AboutUsView, HomeListView

app_name = 'pages'

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('about-us/', AboutUsView.as_view(), name='about')
]

products/urls.py
from django.urls import path
from .views import ProductListView, WishlistView, create_or_delete_wishlist

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('wishlist/user/<int:user_pk>/product/<int:product_pk>',
         create_or_delete_wishlist, name="create_wishlist"),
    path('wishlist/', WishlistView.as_view(), name='wishlist')
]

blogs/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.

class AuthorModel(models.Model):
    full_name = models.CharField(max_length=64)
    avatar = models.ImageField(upload_to='avatar')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _("Author")
        verbose_name_plural = _("Authors")


class TagModel(models.Model):
    title = models.CharField(max_length=64, verbose_name=_("title"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")


class PostModel(models.Model):
    title = models.CharField(max_length=64, verbose_name=_("title"))
    image = models.ImageField(upload_to='image', verbose_name=_("image"))
    banner = models.ImageField(upload_to='banner', verbose_name=_("banner"))
    author = models.ForeignKey(AuthorModel, on_delete=models.CASCADE, verbose_name=_("author"))
    description = models.TextField(verbose_name=_("description"))
    tags = models.ManyToManyField(TagModel, verbose_name=_("tags"))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))

    def __str__(self):
        return self.title
    
    def get_upper_title(self):
        return self.title.upper()
    
    def get_previous_post(self):
        return self.get_previous_by_created_at()
    
    def get_next_post(self):
        return self.get_next_by_created_at()

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")


class CommentModel(models.Model):
    post = models.ForeignKey(
        PostModel, on_delete=models.CASCADE,
            related_name='comments',
            verbose_name=_('comments'))
    name = models.CharField(max_length=64, verbose_name=_('name'))
    email = models.EmailField(max_length=64, verbose_name=_('email'))
    phone = models.CharField(max_length=13, verbose_name=_('phone'))
    comment = models.TextField(verbose_name=_('comment'))

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('created at'),
        null=True)
    
    def __str__(self):
        return f"{self.name}: {self.comment}"
    
    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

contacts/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.

class ContactModel(models.Model):
    name = models.CharField(max_length=64, verbose_name=_('name'))
    email = models.EmailField(max_length=128, verbose_name=_('email'))
    message = models.TextField(verbose_name=_('message'))

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Contact')
        verbose_name_plural = _('Contacts')

    def __str__(self) -> str:
        return f"{self.email}: {self.message}"

blogs/forms.py
from django import forms

from blogs.models import CommentModel


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        exclude = ['id', 'post', 'created_at']

contacts/forms.py
from django import forms

from contacts.models import ContactModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        exclude = ['id', 'created_at', 'updated_at']

blogs/views.py
# Create your views here.
from typing import Any
from django.db import models
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView
from blogs.forms import CommentForm

from blogs.models import PostModel
# Create your views here.

class BlogTemplateView(ListView):
    template_name = 'blog.html'
    model = PostModel

    def get_queryset(self):
        queryset = PostModel.objects.all()
        tag = self.request.GET.get('tag')
        if tag:
            queryset = PostModel.objects.filter(tags__title=tag)

        return queryset


class BlogDetailView(DetailView):
    template_name = 'blog-details.html'
    model = PostModel
    context_object_name = 'post'


def create_post_comment(request, pk):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            post = get_object_or_404(PostModel, pk=pk)
            form = form.save(commit=False)
            form.post = post
            form.save()

            return redirect(reverse('blogs:detail', kwargs={"pk":pk}))
        else:
            return HttpResponse('Please enter a valid data')

contacts/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import TemplateView, CreateView
from contacts.forms import ContactForm
from contacts.models import ContactModel
# Create your views here.

class ContactTemplateView(TemplateView):
    template_name = 'contact.html'


class CreateContactView(CreateView):
    template_name = 'contact.html'
    form_class = ContactForm

    def get_success_url(self):
        return reverse('contacts:page')

templates/blog-details.html
{% extends 'layouts/base.html' %}

{% block content %}
<!-- Blog Details Hero Begin -->
<section class="blog-hero spad">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-9 text-center">
                <div class="blog__hero__text">
                    <h2>{{ post.title }}</h2>
                    <ul>
                        <li>By {{ post.author.full_name }}</li>
                        <li>{{ post.created_at|date:'N d, Y' }}</li>
                        <li>{{ post.comments.all.count }} Comments</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Details Hero End -->

<!-- Blog Details Section Begin -->
<section class="blog-details spad">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="blog__details__pic">
                    <img height="600" width="100%" src="{{ post.banner.url }}" alt="">
                </div>
            </div>
            <div class="col-lg-8">
                <div class="blog__details__content">
                    <div class="blog__details__share">
                        <span>share</span>
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                            <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                    <div class="blog__details__text">
                        <p>{{ post.description }}</p>
                    </div>
                    <div class="blog__details__quote">
                        <i class="fa fa-quote-left"></i>
                        <p>“When designing an advertisement for a particular product many things should be
                            researched like where it should be displayed.”</p>
                        <h6>_ John Smith _</h6>
                    </div>
                    <div class="blog__details__text">
                        <p>Vyo-Serum along with tightening the skin also reduces the fine lines indicating aging of
                            skin. Problems like dark circles, puffiness, and crow’s feet can be control from the
                            strong effects of this serum.</p>
                        <p>Hydroderm is a multi-functional product that helps in reducing the cellulite and giving
                            the body a toned shape, also helps in cleansing the skin from the root and not letting
                            the pores clog, nevertheless also let’s sweeps out the wrinkles and all signs of aging
                            from the sensitive near the eyes.</p>
                    </div>
                    <div class="blog__details__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="blog__details__author">
                                    <div class="blog__details__author__pic">
                                        <img src="{{ post.author.avatar.url }}" alt="">
                                    </div>
                                    <div class="blog__details__author__text">
                                        <h5>{{ post.author.full_name }}</h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="blog__details__tags">
                                    {% for tag in post.tags.all %}
                                    <a href="{% url 'blogs:list' %}?tag={{ tag.title }}">#{{ tag.title }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="blog__details__btns">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                {% if post.get_previous_post %}
                                <a href="{% url 'blogs:detail' pk=post.get_previous_post.pk %}"
                                    class="blog__details__btns__item">
                                    <p><span class="arrow_left"></span> Previous Pod</p>
                                    <h5>{{ post.get_previous_post.title }}</h5>
                                </a>
                                {% endif %}
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                {% if post.get_next_post %}
                                <a href="{% url 'blogs:detail' pk=post.get_next_post.pk %}"
                                    class="blog__details__btns__item blog__details__btns__item--next">
                                    <p>Next Pod <span class="arrow_right"></span></p>
                                    <h5>{{ post.get_next_post.title }}</h5>
                                </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <ul>
                        {% for comment in post.comments.all %}
                        <li class="media">
                            <div class="media-body">
                                <span class="text-muted pull-right">
                                    <small class="text-muted">
                                        {{ comment.created_at|timesince }}
                                    </small>
                                </span>
                                <strong>
                                    {{ comment.name }}
                                </strong>
                                <p>
                                    {{ comment.comment }}
                                </p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>

                    <div class="blog__details__comment">
                        <h4>Leave A Comment</h4>
                        <form method="POST" action="{% url 'blogs:post_comment' pk=post.pk %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-4 col-md-4">
                                    <input name="name" type="text" placeholder="Name">
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <input name="email" type="text" placeholder="Email">
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <input name="phone" type="text" placeholder="Phone">
                                </div>
                                <div class="col-lg-12 text-center">
                                    <textarea name="comment" placeholder="Comment"></textarea>
                                    <button type="submit" class="site-btn">Post Comment</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Details Section End -->
{% endblock %}

templates/shop.html
{% extends 'layouts/base.html' %}

{% block content  %}
{% load static %}
{% load my_tags %}
<style>
    .circle{
      width:33px;
      height:33px;
      border-radius: 50%;
      border-spacing: 2px;
      border: 1px solid black
}
</style>
     <!-- Breadcrumb Section Begin -->
     <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'pages:home' %}">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="shop__sidebar">
                        <div class="shop__sidebar__search">
                            <form action="#">
                                <input name="q" type="text" placeholder="Search...">
                                <button type="submit"><span class="icon_search"></span></button>
                            </form>
                        </div>
                        <div class="shop__sidebar__accordion">
                            <div class="accordion" id="accordionExample">
                                <div class="card">
                                    <div class="card-heading">
                                        <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
                                    </div>
                                    <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                                        <div class="card-body">
                                            <div class="shop__sidebar__categories">
                                                <ul class="nice-scroll">
                                                    {% for category in categories %}
                                                        <li><a href="#">{{ category.title }} ({{ category.products.all.count }})</a></li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-heading">
                                        <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
                                    </div>
                                    <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                                        <div class="card-body">
                                            <div class="shop__sidebar__brand">
                                                <ul>
                                                    {% for brand in brands %}
                                                    <li><a href="#">{{ brand.title }}</a></li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-heading">
                                        <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
                                    </div>
                                    <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                                        <div class="card-body">
                                            <div class="shop__sidebar__price">
                                                <ul>
                                                    <li><a href="#">$0.00 - $50.00</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-heading">
                                        <a data-toggle="collapse" data-target="#collapseFour">Size</a>
                                    </div>
                                    <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                                        <div class="card-body">
                                            <div class="shop__sidebar__size">
                                                {% for size in sizes %}
                                                <label for="{{ size.title }}">{{ size.title }}
                                                    <input type="radio" id="xs">
                                                </label>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-heading">
                                        <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
                                    </div>
                                    <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                                        <div class="card-body">
                                            {% for color in colors %}
                                                <label>
                                                    <a href="/products/?color={{ color.title }}"><div class="circle" style="background-color: {{ color.color }};"></div></a>
                                                </label>
                                                {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="shop__product__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__left">
                                    <p>Showing 1–12 of 126 results</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <form id="sortForm" method="GET" action="{% url 'products:list' %}">
                                    {% csrf_token %}
                                    <div class="shop__product__option__right">
                                        <p>Sort by Price:</p>
                                        <select name="sort" id="sort" onchange="submitForm()">
                                            <option value="">---</option>
                                            <option value="asc">Low to High</option>
                                            <option value="desc">High to Low</option>
                                        </select>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for product in products %}
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg="{{ product.image.url }}">
                                    {% if product.is_new %}
                                        <span style="background-color: #111111; color: #ffffff;" class="label">New</span>
                                    {% endif %}
                                    <ul class="product__hover">
                                        <li><a href="{% url 'products:create_wishlist' user_pk=request.user.pk product_pk=product.pk %}">
                                            {% if product|in_wishlist:request.user %}
                                            <img src="{% static 'img/heartr.png' %}" alt="">
                                            {% else %}
                                            <img src="{% static 'img/heartwhite.png' %}" alt="">
                                            {% endif %}
                                        </a></li>
                                        <li><a href="#"><img src="{% static 'img/icon/compare.png' %}" alt=""> <span>Compare</span></a>
                                        </li>
                                        <li><a href="#"><img src="{% static 'img/icon/search.png' %}" alt=""></a></li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6>{{ product.title }}</h6>
                                    <a href="#" class="add-cart">+ Add To Cart</a>
                                    <div class="rating">
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    </div>
                                    <h5>${{ product.price }}</h5>
                                    <div class="product__color__select">
                                        <label for="pc-4">
                                            <input type="radio" id="pc-4">
                                        </label>
                                        <label class="active black" for="pc-5">
                                            <input type="radio" id="pc-5">
                                        </label>
                                        <label class="grey" for="pc-6">
                                            <input type="radio" id="pc-6">
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="product__pagination">
                                <a class="active" href="#">1</a>
                                <a href="#">2</a>
                                <a href="#">3</a>
                                <span>...</span>
                                <a href="#">21</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->
    <script>
        function submitForm() {
            document.getElementById("sortForm").submit();
        }
    </script>
{% endblock %}

templates/wishlist.html
{% extends 'layouts/base.html' %}

{% block content  %}
{% load static %}
{% load my_tags %}
<style>
    .circle{
      width:33px;
      height:33px;
      border-radius: 50%;
      border-spacing: 2px;
      border: 1px solid black
}
</style>
     <!-- Breadcrumb Section Begin -->
     <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'pages:home' %}">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="row">
                        {% for wishlist in wishlists %}
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg="{{ wishlist.product.image.url }}">
                                    {% if wishlist.product.is_new %}
                                        <span style="background-color: #111111; color: #ffffff;" class="label">New</span>
                                    {% endif %}
                                    <ul class="product__hover">
                                        <li><a href="{% url 'products:create_wishlist' user_pk=request.user.pk product_pk=wishlist.product.pk %}">
                                            {% if wishlist.product|in_wishlist:request.user %}
                                            <img src="{% static 'img/heartr.png' %}" alt="">
                                            {% else %}
                                            <img src="{% static 'img/heartwhite.png' %}" alt="">
                                            {% endif %}
                                        </a></li>
                                        <li><a href="#"><img src="{% static 'img/icon/compare.png' %}" alt=""> <span>Compare</span></a>
                                        </li>
                                        <li><a href="#"><img src="{% static 'img/icon/search.png' %}" alt=""></a></li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6>{{ wishlist.product.title }}</h6>
                                    <a href="#" class="add-cart">+ Add To Cart</a>
                                    <div class="rating">
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    </div>
                                    <h5>${{ wishlist.product.price }}</h5>
                                    <div class="product__color__select">
                                        <label for="pc-4">
                                            <input type="radio" id="pc-4">
                                        </label>
                                        <label class="active black" for="pc-5">
                                            <input type="radio" id="pc-5">
                                        </label>
                                        <label class="grey" for="pc-6">
                                            <input type="radio" id="pc-6">
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}